config/routes.rb
Rails.application.routes.draw do

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users" do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]


  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  #*** end of default routes of Clearance

  resources :users, controller: "users", only: :show
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  root 'welcome#index'
  resources :listings do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:destroy, :index] do
    resources :payments, only: [:new, :create]
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :bookings
  mount_uploaders :images, ImageUploader

  paginates_per 5
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
     before_action :find_listing, only: [:show,:edit, :update]

  def index
    @listings = Listing.order(updated_at: :desc).page params[:page]
  end

  def new
    @listing = Listing.new
      # authorization code
      # end authorization code

      # other code to make the new action work!
  end


  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    byebug
    if  @listing.save
      redirect_to listing_path(@listing)
    end
  end

  def show
    @booking = @listing.bookings.new
  end

  def edit

  end

  def update
    if @listing.update(listing_params)
      flash[:success] = "Successfully updated the listing"
      redirect_to @listing
    else
      flash[:danger] = "Error updating listing"
      render :edit
    end
  end

private
  def find_listing
  @listing = Listing.find (params[:id])
  end

  def listing_params
    params.require(:listing).permit(:title, :description, :max_guest, :price, {images:[]})
  end


end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for @listing do |f| %>
<div>
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>

<div>
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>

<div>
  <%= f.label :max_guest %>
  <%= f.number_field :max_guest %>
</div>

<div>
  <%= f.label :price %>
  <%= f.number_field :price %>
</div>

<p>
   <%= f.file_field :images, multiple: true %>
 </p>

<%= f.submit "Submit" %>
<% end %>

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>
<%= render "form"%>

app/views/listings/index.html.erb
  <div class="jumbotron">
    <br/>
    <br/>
    <br/>
    <h1>WELCOME TO HOME</h1>
    <br/>
    <br/>
    <p>FIND A PLACE TO STAY</p>
  </div>


<%= link_to "Create New Listing", new_listing_path, class: 'btn btn-primary' %>

  <% @listings.each do |listing| %>
    <div class="row">
      <div class="col-md-4 col-md-offset-2 col-xs-4 col-xs-offset-2">
        <h3 class="text-center">
          <%= link_to listing.title, listing_path(listing) %>
        </h3>
      </div>
      <div class="col-md-4 col-xs-4">
        <% if listing.images.empty? %>
          <h3 class="text-center">
            No Image Available
          </h3>
        <% else %>
          <%= image_tag listing.images.first.thumb %>
        <% end %>
      </div>
    </div>
  <% end %>
<%= paginate @listings %>

app/views/listings/new.html.erb
<h1>New Listing</h1>
<%= render "form"%>

app/views/listings/show.html.erb
<h1>Title: <%= @listing.title %></h1>
<% @listing.images.each do |image| %>
  <%= image_tag image %>
<% end %>
<div>
  Posted by<%= @listing.user.email%>
</div>
<p>Description: <%= @listing.description %></p>
<p>Max Guests: <%= @listing.max_guest %></p>
<p>Price: <%= @listing.price %></p>
<%= link_to "Edit", edit_listing_path(@listing) %>

<%= form_for [@listing, @booking] do |form| %>
  <div class="form_goup">
    <%= form.label :start_date %>
    <%= form.text_field :start_date, class: "datepicker form-control" %>
  </div>
  <div class="form_goup">
    <%= form.label :end_date %>
    <%= form.text_field :end_date, class: "datepicker form-control " %>
  </div>
  <div class="form_goup">
    <%= form.label :num_guests %>
    <%= form.number_field :num_guests, class: "form-control" %>
  </div>
  <div class="form_goup">
    <%= form.submit "Submit", class: "btn btn-default" %>
  </div>
<% end %>