config/routes.rb
Rails.application.routes.draw do

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users" do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]


  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  #*** end of default routes of Clearance

  resources :users, controller: "users", only: :show
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  root 'welcome#index'
  resources :listings do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:destroy, :index] do
    resources :payments, only: [:new, :create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  validates :email, uniqueness: true
   has_many :authentications, :dependent => :destroy
   has_many :listings
   has_many :bookings

   enum role: ["user", "admin", "superadmin"]

   def self.create_with_auth_and_hash(authentication,auth_hash)
     create! do |u|
       #u.first_name = auth_hash["info"]["first_name"]
       # u.last_name = auth_hash["info"]["last_name"]
       # u.friendly_name = auth_hash["info"]["name"]
       u.email = auth_hash["extra"]["raw_info"]["email"]
       u.password = SecureRandom.hex(6)
       u.authentications<<(authentication)
     end
   end

   def fb_token
     x = self.authentications.where(:provider => :facebook).first
     return x.token unless x.nil?
   end


   # def password_optional?
   #   true
   # end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show,:edit, :update]

  def index
    @users = User.all
  end

  def show
    @bookings = @user.bookings
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render "new"
    end
  end

  def edit
  end

  def update
  if @user.update(user_params)
    flash[:success] = "Successfully updated the user"
    redirect_to @user
  else
    flash[:danger] = "Error updating user"
    render :edit
  end
end

  def find_user
  @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/index.html.erb
<% if current_user.user? %>
<p>You are not allowed </p>
<% else %>
<table>
  <% @users.each do |user| %>
  <tr>
    <td><%= link_to user.email, user %></td>
  </tr>
<% end %>
</table>
<%end%>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Email: <%= @user.email %></h1>

<%= link_to "Edit", edit_user_path(@user) %>

<h2>Bookings</h2>
<table>
<tr>
  <th>Listing Title</th>
  <th>Start Date</th>
  <th>End Dates</th>
  <th>Num_guests</th>
  <th>Total_price</th>
  <th>Action</th>
</tr>

<% @bookings.each do |booking| %>
<tr>
  <td><%= link_to booking.listing.title, booking.listing  %></td>
  <td><%= booking.start_date.strftime('%d,%B,%Y') %></td>
  <td><%= booking.end_date.strftime('%d,%B,%Y') %></td>
  <td><%= booking.num_guests %></td>
  <td><%= booking.total_price %></td>
  <td><%= link_to "Cancel Booking", booking_path(booking), method: :delete %></td>
  <td><%= link_to "Pay", new_booking_payment_path(booking) %></td>
</tr>
<% end %>
</table>