config/routes.rb
Rails.application.routes.draw do

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users" do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]


  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  #*** end of default routes of Clearance

  resources :users, controller: "users", only: :show
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  root 'welcome#index'
  resources :listings do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:destroy, :index] do
    resources :payments, only: [:new, :create]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
  <%= csrf_meta_tag %>
</head>
<body>
  <%= link_to "Home", root_path %>
  <%= link_to "All Listing", listings_path %>
  <%= link_to "All Booking", bookings_path %>
  <%= link_to "Profile", user_path(current_user) %>
  <div id="header">
    <% if signed_in? -%>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path %>
      <%= link_to "Sign in with Facebook", "/auth/facebook" %>
    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>
  <%= yield %>
</body>
</html>